<?php

return [
    'delivery_man_permissions' => [
        'delivery_parcel_create',
        'delivery_parcel_read',
        'delivery_parcel_update',
        'delivery_parcel_delete',
    ],
    'parcel_types_for_merchant' => [
        'next_day',
        // 'frozen',
        // 'sub_city',
        'sub_urban_area',
        // 'third_party_booking',
    ],
    'parcel_status' => [
        'pending',
        'pickup-assigned',
        're-schedule-pickup',
        'received-by-pickup-man',
        'received',
        'transferred-to-branch',
        'transferred-received-by-branch',
        'delivery-assigned',
        're-schedule-delivery',
        'returned-to-warehouse',
        'return-assigned-to-merchant',
        'partially-delivered',
        'delivered',
        'returned-to-merchant',
        're-request',
        'cancel',
        'deleted',
    ],

    'banks' => [
        'ab_bank_ltd',
        'agrani_bank_ltd',
        "al_afarah_islami_bank_ltd",
        'bank_asia_ltd',
        "brac_bank_ltd",
        'city_bank_ltd',
        'dbbl_agent_banking',
        "dhaka_bank_limited",
        "dutch_bangla_bank_ltd",
        "eastern_bank_ltd",
        "first_security_islami_bank",
        "exim_bank_bangladesh_ltd",
        "ific_bank_ltd",
        "islami_bank_bangladesh_ltd",
        "jamuna_bank_ltd",
        "mercantile_bank_ltd",
        "meghna_bank_ltd",
        "mutual_trust_bank_ltd",
        "national_bank_ltd",
        "nrb_bank_ltd",
        "nrb_commercial_bank_ltd",
        "one_bank_ltd",
        "prime_bank_ltd",
        "shahjalal_islami_bank_ltd",
        "southeast_bank_ltd",
        "standard_bank_ltd",
        "standard_chartered_bank",
        "the_premiere_bank_ltd",
        "trust_bank_ltd",
        "united_commercial_bank_ltd",
        "uttara_bank_ltd",
	"midland_bank_ltd",
    ],
    'account_methods' => [
        'cash',
        'bank',
        'bkash',
        'nogod',
        'rocket'
    ],
    'account_types' => [
        'personal',
        'merchant',
    ],
    'events' =>[
        'parcel_create_event',
        'assign_pickup_man_event',
        'parcel_re_schedule_pickup_event',
        'parcel_received_event',
        'assign_delivery_man_event',
        'parcel_re_schedule_delivery_event',
        'parcel_delivered_event',
        'parcel_return_to_wirehouse',
        'parcel_return_assign_to_merchant_event',
        'parcel_returned_to_merchant_event',
        'parcel_cancel_event',
        'parcel_re_request_event',
        'parcel_update_event',
    ],

    'paginate' => 20, //for all index pagination except parcel of admin dashboard
    'api_paginate' => 15, //for all api parcel Listing
    'parcel_merchant_paginate' => 50, //for all parcel / merchant listing

    'delivery_re_schedule_reasons' => [
        're_schedule_reasons1',
        're_schedule_reasons2',
        're_schedule_reasons3',
        're_schedule_reasons4',
        're_schedule_reasons5',
        're_schedule_reasons6',
        're_schedule_reasons7',
        're_schedule_reasons8',
    ],
    'cancel_predefined_reasons' => [
        'cancel_reasons1',
        'cancel_reasons2',
        'cancel_reasons3',
        'cancel_reasons4',
    ],
    'pickup_re_schedule_reasons' => [
        'customer_phone_off',
        'customer_did_not_pickup',
    ],
];
